@api-key={{$dotenv AZURE_SEARCH_API_KEY}}
@uri-host={{$dotenv AZURE_SEARCH_ENDPOINT}}
@api-version=2025-11-01-Preview

@name-prefix=ks-disneylandmap-demo
@data-source-name={{name-prefix}}-datasource

@blob-connection-string={{$dotenv AZURE_BLOB_CONNECTION_STRING}}
@blob-container-name={{$dotenv AZURE_BLOB_CONTAINER_NAME}}

### Create datasource
PUT {{uri-host}}/datasources/{{data-source-name}}?api-version={{api-version}}
api-key: {{api-key}}
Content-Type: application/json

{
  "name": "{{data-source-name}}",
  "description": "Data source for knowledge source '{{name-prefix}}'",
  "type": "azureblob",
  "subtype": null,
  "indexerPermissionOptions": [],
  "credentials": {
    "connectionString": "{{blob-connection-string}}"
  },
  "container": {
    "name": "{{blob-container-name}}",
    "query": null
  },
  "dataChangeDetectionPolicy": null,
  "dataDeletionDetectionPolicy": null,
  "encryptionKey": null,
  "identity": null
}