@api-key={{$dotenv AZURE_SEARCH_API_KEY}}
@uri-host={{$dotenv AZURE_SEARCH_ENDPOINT}}
@api-version=2025-11-01-Preview

@name-prefix=<Name Prefix>
@index-name={{name-prefix}}-index

### Search query
POST {{uri-host}}/indexes/{{index-name}}/docs/search?api-version={{api-version}}
api-key: {{api-key}}
Content-Type: application/json

{
  "search": "*",
  "select": "snippet"
}